# Generated by Django 6.1 on 2026-08-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_emailtemplate_emailcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_recipients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('SENDING', 'Sending in Background'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=15),
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='SENT', max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.emailcampaign')),
            ],
        ),
    ]
